import React, { useState } from 'react';
import { useLanguage } from '../../context/LanguageContext';
import { Modal } from '../layout/Modal';
import { BookOpen, Calendar, User, ArrowRight, Tag } from 'lucide-react';

export const BlogList = ({ openQuoteModal }) => {
  const { t } = useLanguage();
  const [selectedArticle, setSelectedArticle] = useState(null);
  const [activeCategory, setActiveCategory] = useState('All');

  const articlesData = [
    {
      id: 1,
      slug: "solar-panel-cleaning-guide",
      title: "Solar Panel Cleaning & Maintenance Guide for Maximum Generation",
      metaDesc: "Learn how proper solar panel cleaning every 15 days can boost electricity output by up to 25%. Expert maintenance tips for rooftop solar owners.",
      category: "Maintenance",
      author: "Solar EPC Engineering Team",
      date: "September 2, 2024",
      readTime: "4 min read",
      image: "https://images.unsplash.com/photo-1509391365360-2e959784a276?q=80&w=800&auto=format&fit=crop",
      content: `Solar panels are designed to last 25 to 30 years, but dust, bird droppings, and industrial smog can create a layer on the panel glass, reducing light absorption. Regular maintenance ensures your system generates maximum kWh units daily. Clean panels using soft plain water every 15 days early in the morning before sunlight heats up the panel glass.`
    },
    {
      id: 2,
      slug: "pm-surya-ghar-subsidy-guide-2024",
      title: "PM Surya Ghar Subsidy Guide: How to Claim up to ₹78,000 Direct Credit",
      metaDesc: "Step-by-step application walkthrough for claiming Central Government rooftop solar subsidy under PM Surya Ghar Muft Bijli Yojana in Maharashtra.",
      category: "Subsidy Guide",
      author: "MSEDCL Liaisoning Expert",
      date: "August 28, 2024",
      readTime: "5 min read",
      image: "https://images.unsplash.com/photo-1508873696983-2df515122519?q=80&w=800&auto=format&fit=crop",
      content: `The PM Surya Ghar scheme allows homeowners to claim ₹30,000 for 1 kW, ₹60,000 for 2 kW, and ₹78,000 for 3 kW+ rooftop solar installations. Learn how MSEDCL approved vendors complete technical feasibility and direct bank transfer (DBT) processing.`
    },
    {
      id: 3,
      slug: "net-metering-msedcl-explained",
      title: "What is MSEDCL Net Metering & How Does it Zero Your Electricity Bill?",
      metaDesc: "Understand bi-directional net meters, solar export units, banking period, and annual electricity bill settlement with MSEDCL.",
      category: "Technology",
      author: "Green Leaf Technical Director",
      date: "August 20, 2024",
      readTime: "6 min read",
      image: "https://images.unsplash.com/photo-1613665813446-82a78c468a1d?q=80&w=800&auto=format&fit=crop",
      content: `Net metering tracks the electricity generated by your rooftop solar panels versus the grid power imported at night. Surplus power exported during peak sunlight hours earns you units credited on your MSEDCL bill.`
    },
    {
      id: 4,
      slug: "hybrid-vs-on-grid-solar-system",
      title: "Hybrid vs On-Grid Solar Systems: Which One Should You Install?",
      metaDesc: "Comparing costs, battery backup benefits, grid dependence, and ROI of On-Grid vs Hybrid Solar Systems for homes and commercial setups.",
      category: "Technology",
      author: "Solar EPC Engineering Team",
      date: "August 15, 2024",
      readTime: "5 min read",
      image: "https://images.unsplash.com/photo-1558441719-443b34438ad9?q=80&w=800&auto=format&fit=crop",
      content: `On-Grid solar is the most cost-effective option for areas with minimal power cuts, feeding surplus energy back into the DISCOM grid. Hybrid solar adds lithium LiFePO4 battery backup for zero downtime during load shedding.`
    },
    {
      id: 5,
      slug: "commercial-industrial-solar-roi-tax-benefits",
      title: "Commercial & Industrial Solar Benefits: 40% Accelerated Depreciation & ROI",
      metaDesc: "How commercial factories and offices recover solar plant installation costs in 3 to 4 years while taking advantage of IT tax exemptions.",
      category: "ROI & Savings",
      author: "Green Leaf Finance Team",
      date: "August 10, 2024",
      readTime: "7 min read",
      image: "https://images.unsplash.com/photo-1548611635-b6e7827d7d4a?q=80&w=800&auto=format&fit=crop",
      content: `Commercial enterprises pay high electricity tariff rates in Maharashtra. Installing a 50 kW to 500 kW industrial solar plant delivers up to 30% IRR returns and allows 40% accelerated depreciation in year one.`
    },
    {
      id: 6,
      slug: "solar-rooftop-calculator-guide",
      title: "How to Calculate Rooftop Solar System Capacity for Your Property",
      metaDesc: "Simple math formula to convert monthly electricity bill into exact kW requirement, panel area, and estimated monthly generation.",
      category: "ROI & Savings",
      author: "Technical Operations Manager",
      date: "August 02, 2024",
      readTime: "4 min read",
      image: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?q=80&w=800&auto=format&fit=crop",
      content: `To calculate your solar requirement: divide your monthly electricity bill by ₹8.5 per unit tariff to get monthly kWh units. Divide total monthly units by 135 to find the required kW capacity.`
    }
  ];

  const categories = ["All", "Subsidy Guide", "Maintenance", "Technology", "ROI & Savings"];

  const filteredArticles = activeCategory === "All"
    ? articlesData
    : articlesData.filter(a => a.category === activeCategory);

  return (
    <section className="py-16 bg-slate-50 border-b border-slate-200/60 font-sans" id="blog">
      <div className="max-w-7xl mx-auto px-4">
        
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto space-y-3 mb-10">
          <div className="inline-flex items-center space-x-2 bg-green-50 px-3.5 py-1.5 rounded-full border border-green-100 text-xs font-extrabold text-solar-green uppercase tracking-wider">
            <BookOpen className="w-4 h-4" />
            <span>{t('blog.title')}</span>
          </div>
          <h2 className="text-2xl sm:text-4xl font-extrabold text-solar-blue tracking-tight">
            {t('blog.subtitle')}
          </h2>
        </div>

        {/* Category Filters */}
        <div className="flex flex-wrap justify-center gap-2 mb-10">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                activeCategory === cat
                  ? 'bg-solar-green text-white shadow-md'
                  : 'bg-white text-slate-700 hover:bg-slate-100 border border-slate-200'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Articles Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredArticles.map((article) => (
            <div 
              key={article.id}
              className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm hover:shadow-solar-lg transition-all duration-300 flex flex-col justify-between group space-y-4"
            >
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="bg-solar-green text-white text-[10px] font-extrabold px-2.5 py-1 rounded-md uppercase tracking-wider shadow-xs">
                    {article.category}
                  </span>
                  <span className="text-[10px] text-slate-400 font-semibold flex items-center space-x-1">
                    <Calendar className="w-3 h-3 text-solar-amber" />
                    <span>{article.date}</span>
                  </span>
                </div>

                <h3 className="text-base font-extrabold text-solar-blue group-hover:text-solar-green transition-colors leading-snug">
                  {article.title}
                </h3>

                <p className="text-xs text-slate-600 font-normal leading-relaxed line-clamp-3">
                  {article.metaDesc}
                </p>
              </div>

              <div className="pt-2">
                <button
                  onClick={() => setSelectedArticle(article)}
                  className="w-full bg-slate-50 hover:bg-solar-blue hover:text-white text-solar-blue text-xs font-bold py-2.5 rounded-xl transition-colors flex items-center justify-center space-x-1.5 border border-slate-200"
                >
                  <span>{t('blog.readMore')}</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          ))}
        </div>

        {/* Article Reader Modal */}
        <Modal
          isOpen={!!selectedArticle}
          onClose={() => setSelectedArticle(null)}
          title={selectedArticle?.title || "Article Reader"}
        >
          {selectedArticle && (
            <div className="space-y-5 font-sans">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div className="flex items-center space-x-4 text-xs text-slate-500 font-semibold">
                  <span className="flex items-center space-x-1">
                    <User className="w-3.5 h-3.5 text-solar-green" />
                    <span>{selectedArticle.author}</span>
                  </span>
                  <span>•</span>
                  <span>{selectedArticle.date}</span>
                </div>
                <span className="bg-solar-green text-white text-[10px] font-extrabold px-2.5 py-1 rounded-md uppercase">
                  {selectedArticle.category}
                </span>
              </div>

              <div className="text-xs sm:text-sm text-slate-700 leading-relaxed font-normal space-y-4">
                <p className="font-semibold text-slate-900 text-sm">
                  {selectedArticle.metaDesc}
                </p>
                <p>
                  {selectedArticle.content}
                </p>
                <p>
                  For personalized solar feasibility analysis and MSEDCL net metering assistance on your building, get in touch with Green Leaf Energy Solution today.
                </p>
              </div>

              {/* Contextual Article CTA */}
              <div className="pt-4 border-t border-slate-100 bg-green-50 p-4 rounded-xl flex flex-col sm:flex-row items-center justify-between gap-3">
                <span className="text-xs font-bold text-solar-blue">Ready to Install Solar on Your Roof?</span>
                <button
                  onClick={() => {
                    setSelectedArticle(null);
                    openQuoteModal();
                  }}
                  className="bg-solar-green text-white px-4 py-2 rounded-lg text-xs font-bold shadow hover:bg-solar-green-dark transition-colors"
                >
                  Get Free Consultation
                </button>
              </div>
            </div>
          )}
        </Modal>

      </div>
    </section>
  );
};
